import nodemailer from "nodemailer";
import { createDecipheriv, createHash, randomInt } from "node:crypto";
import { query } from "@/server/db/tx";

type SmtpConfig = { senderEmail: string; host: string; port: number; useSsl: boolean; password: string };
function decrypt(value: string): string { const secret = process.env.SMTP_STATE_KEY || process.env.TAOBAO_STATE_KEY; if (!secret) throw new Error("SMTP_STATE_KEY is not configured"); const key = Buffer.from(secret, "base64"); const stored = JSON.parse(value) as { iv: string; tag: string; data: string }; const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(stored.iv, "base64")); decipher.setAuthTag(Buffer.from(stored.tag, "base64")); return Buffer.concat([decipher.update(Buffer.from(stored.data, "base64")), decipher.final()]).toString("utf8"); }
function digest(code: string) { return createHash("sha256").update(code).digest("hex"); }
async function configFor(userId?: string): Promise<SmtpConfig | null> { if (userId) { const result = await query<{ sender_email: string; host: string; port: number; use_ssl: boolean; password_ciphertext: string }>("SELECT sender_email, host, port, use_ssl, password_ciphertext FROM user_smtp_settings WHERE user_id=$1", [userId]); const row = result.rows[0]; if (row) return { senderEmail: row.sender_email, host: row.host, port: row.port, useSsl: row.use_ssl, password: decrypt(row.password_ciphertext) }; } if (process.env.SMTP_USER && process.env.SMTP_PASS && process.env.SMTP_HOST) return { senderEmail: process.env.SMTP_USER, host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 465), useSsl: process.env.SMTP_SSL !== "false", password: process.env.SMTP_PASS }; return null; }
export async function sendVerificationCode(userId: string | undefined, email: string, purpose: "registration" | "payment") { const config = await configFor(userId); if (!config) throw new Error("请先配置 SMTP 发件邮箱。"); const code = String(randomInt(100000, 1000000)); await query("DELETE FROM email_verifications WHERE email=$1 AND purpose=$2", [email.toLowerCase(), purpose]); await query("INSERT INTO email_verifications (email, purpose, code_hash, expires_at) VALUES ($1,$2,$3,now()+interval '5 minutes')", [email.toLowerCase(), purpose, digest(code)]); const transport = nodemailer.createTransport({ host: config.host, port: config.port, secure: config.useSsl, auth: { user: config.senderEmail, pass: config.password } }); await transport.sendMail({ from: config.senderEmail, to: email, subject: purpose === "payment" ? "AI 代购支付验证码" : "AI 代购注册验证码", text: `你的验证码是 ${code}，5 分钟内有效。` }); }
export async function consumeVerificationCode(email: string, purpose: "registration" | "payment", code: string) { const result = await query("UPDATE email_verifications SET consumed_at=now() WHERE id=(SELECT id FROM email_verifications WHERE email=$1 AND purpose=$2 AND code_hash=$3 AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1) RETURNING id", [email.toLowerCase(), purpose, digest(code)]); return Boolean(result.rowCount); }
