"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api, ApiError } from "@/lib/api";
export function RegisterForm() { const router = useRouter(); const [email, setEmail] = useState(""); const [displayName, setDisplayName] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, start] = useTransition(); function sendCode() { start(async () => { try { await api("/api/auth/verification", { method: "POST", json: { email, purpose: "registration" } }); setSent(true); setError(null); } catch (e) { setError(e instanceof ApiError ? e.message : "验证码发送失败，请检查 SMTP 配置"); } }); } function submit(event: React.FormEvent) { event.preventDefault(); start(async () => { try { await api("/api/auth/register", { method: "POST", json: { email, displayName, password, code } }); router.replace("/"); router.refresh(); } catch (e) { setError(e instanceof ApiError ? e.message : "注册失败"); } }); } return <Card><CardContent className="pt-6"><form onSubmit={submit} className="space-y-4"><div className="space-y-1.5"><Label>昵称</Label><Input value={displayName} onChange={(e) => setDisplayName(e.target.value)} required /></div><div className="space-y-1.5"><Label>电子邮箱</Label><Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="flex gap-2"><Input placeholder="6位验证码" value={code} onChange={(e) => setCode(e.target.value)} required /><Button type="button" variant="outline" onClick={sendCode} disabled={pending || !email}>{sent ? "重新发送" : "发送验证码"}</Button></div><div className="space-y-1.5"><Label>密码</Label><Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="至少8位，含字母和数字" required /></div>{error && <p className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={pending}>{pending ? "处理中…" : "注册并登录"}</Button><p className="text-center text-sm text-zinc-500">已有账号？<Link className="text-zinc-900 underline" href="/login">返回登录</Link></p></form></CardContent></Card>; }
